server.port=8088
spring.application.name=ms-report

# ── Base de datos ──────────────────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://mysql-report:3306/report_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=petmatch2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA ────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── JWT ────────────────────────────────────────────────────────────────────
jwt.secret=PetMatchSecretKey2026_SanosYSalvos
jwt.expiration=86400000

# ── Eureka — Service Discovery ─────────────────────────────────────────────
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ── RabbitMQ — Mensajería asíncrona ───────────────────────────────────────
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=petmatch
spring.rabbitmq.password=petmatch2026
spring.rabbitmq.virtual-host=/

ms.pet.url=http://ms-pet:8081
ms.report-type.url=http://ms-report-type:8086
ms.report-status.url=http://ms-report-status:8087

# Circuit Breaker
resilience4j.circuitbreaker.instances.reportService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reportService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reportService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.reportService.waitDurationInOpenState=5s
resilience4j.retry.instances.reportService.maxAttempts=3
resilience4j.retry.instances.reportService.waitDuration=1s
