server.port=8080
spring.application.name=api-gateway

# ── Eureka — descubrimiento de servicios ───────────────────────────────────
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ── Rutas del Gateway (lb:// usa Eureka para resolver la URL) ──────────────
spring.cloud.gateway.routes[0].id=ms-pet
spring.cloud.gateway.routes[0].uri=lb://ms-pet
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pet/**

spring.cloud.gateway.routes[1].id=ms-race
spring.cloud.gateway.routes[1].uri=lb://ms-race
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/race/**

spring.cloud.gateway.routes[2].id=ms-animal-type
spring.cloud.gateway.routes[2].uri=lb://ms-animal-type
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/animal-type/**

spring.cloud.gateway.routes[3].id=ms-size
spring.cloud.gateway.routes[3].uri=lb://ms-size
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/size/**

spring.cloud.gateway.routes[4].id=ms-pet-color
spring.cloud.gateway.routes[4].uri=lb://ms-pet-color
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/pet-color/**,/api/color/**

spring.cloud.gateway.routes[5].id=ms-report
spring.cloud.gateway.routes[5].uri=lb://ms-report
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/report/**

spring.cloud.gateway.routes[6].id=ms-report-type
spring.cloud.gateway.routes[6].uri=lb://ms-report-type
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/report-type/**

spring.cloud.gateway.routes[7].id=ms-report-status
spring.cloud.gateway.routes[7].uri=lb://ms-report-status
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/report-status/**

# ── JWT ────────────────────────────────────────────────────────────────────
jwt.secret=PetMatchSecretKey2026_SanosYSalvos

# ── Logs ───────────────────────────────────────────────────────────────────
logging.level.org.springframework.cloud.gateway=INFO
