services:
  rol-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rol-service
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/rol_db?createDatabaseIfNotExist=true&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    restart: unless-stopped
